
services:
  postgres:
    image: postgres:18
    container_name: rag_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
     - rag_postgres_data:/var/lib/postgresql

volumes:
  rag_postgres_data: